//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KayMVC.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class GraphicsSample
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GraphicsSample()
        {
            this.WritingSamples = new HashSet<WritingSample>();
        }
    
        public int GraphicID { get; set; }
        public string ImageName { get; set; }
        public bool IsActive { get; set; }
        public string Information { get; set; }
        public string GraphicTitle { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WritingSample> WritingSamples { get; set; }
    }
}
