//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KayMVC.DATA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class kaylahSiteEntities : DbContext
    {
        public kaylahSiteEntities()
            : base("name=kaylahSiteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<About> Abouts { get; set; }
        public virtual DbSet<GraphicsSample> GraphicsSamples { get; set; }
        public virtual DbSet<Picture> Pictures { get; set; }
        public virtual DbSet<WritingSample> WritingSamples { get; set; }
        public virtual DbSet<ResumeUpload> ResumeUploads { get; set; }
    }
}
