//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KayMVC.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Responsibility
    {
        public int ResponsibilityID { get; set; }
        public int EntryID { get; set; }
        public string Responsibility1 { get; set; }
    
        public virtual ResumeJobEntry ResumeJobEntry { get; set; }
    }
}
