//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KayMVC.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResumeJobEntry
    {
        public int EntryID { get; set; }
        public int CompanyID { get; set; }
        public System.DateTime DateBegin { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public bool isRelevant { get; set; }
        public string Title { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Responsibility Responsibility { get; set; }
    }
}
