//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KayMVC.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class WritingSample
    {
        public int SampleID { get; set; }
        public string SampleTitle { get; set; }
        public string SampleContext { get; set; }
        public string SampleAdditionalContext { get; set; }
        public Nullable<int> GraphicPairing { get; set; }
    
        public virtual GraphicsSample GraphicsSample { get; set; }
    }
}
